- hosts: all
  sudo: true
  tasks:
    - command: yum-config-manager --enable epel
    - yum: name=git
    - yum: name=docker-io
    - service: name=docker state=started
    - git: name=https://github.com/discourse/discourse_docker dest=/opt/discourse_docker
    - command: rm -f ~/.ssh/id_rsa
    - command: ssh-keygen -t rsa -q -f ~/.ssh/id_rsa -P ''
    - include: swap.yaml
      when: not vagrant
